# Traffic Split
apiVersion: split.smi-spec.io/v1alpha1
kind: TrafficSplit
metadata:
  name: service-split
  namespace: squidgames
spec:
  service: grpc-pubsub-client-service
  backends:
  - service: grpc-pubsub-client-service
    weight: 333m
  - service: grpc-rabbit-client-service
    weight: 334m
  - service: grpc-kafka-client-service
    weight: 333m

