version: "3.5"

services:

  db:
    command: bash -c "redis-server --appendonly yes"
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis-volume:/data
    networks:
      - sopes-redis

networks:
  
  sopes-redis:
    driver: bridge