# Pod Kill
apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: pod-kill
  namespace: chaos-testing
spec:
  action: pod-kill
  mode: one
  selector:
    namespaces:
      - squidgames
    labelSelectors:
      "app": "grpc-pubsub-client"
  scheduler:
    cron: '@every 1m'