# Pod Failure
apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: pod-failure
  namespace: chaos-testing
spec:
  action: pod-failure
  mode: one
  value: ''
  selector:
    namespaces:
      - squidgames
    labelSelectors:
      "app": "Nombre"  # Nombre De La App
  duration: '30s'
  scheduler:
    cron: '@every 1m'