# Pod Failure
apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: pod-failure
  namespace: chaos-testing
spec:
  action: pod-failure
  mode: one
  selector:
    namespaces:
      - squidgames
    labelSelectors:
      "app": grpc-pubsub-client
  duration: '30s'
  scheduler: '@every 10s'