# Container Kill
apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: container-kill
  namespace: chaos-testing
spec:
  action: container-kill
  mode: one
  containerName: grpc-pubsub-client
  selector:
    namespaces:
      - squidgames
    labelSelectors:
      "app": grpc-pubsub-client
  duration: '30s'
  scheduler: '@every 10s'