# Stress Chaos  
apiVersion: chaos-mesh.org/v1alpha1
kind: StressChaos
metadata:
  name: burn-cpu
  namespace: chaos-testing
spec:
  mode: one
  selector:
    namespaces:
      - squidgames
  stressors:
    cpu:
      workers: 1
  duration: '15s'
  scheduler:
    cron: '@every 2m'